const express = require('express');
const router = express.Router();
const homeRoutes = require('./homeRouter');
const feedbackformRoutes = require('./feedbackformRouter');
const requestRoutes = require('./requestRouter');
const requestformRoutes = require('./requestformRouter');
const comingsoonRoutes = require('./comingsoonRouter');
const errorRoutes = require('./errorRouter');
const aiRoutes = require('./aiRouter');
const profileRoutes = require('./profileRouter');
const insightsRoutes = require('./insightsRouter');
const insightsApiRoutes = require('./insightsApiRouter');
const datasetRoutes = require('./datasetRouter');
const datasetApiRoutes = require('./datasetApiRouter');
const dashboardRoutes = require('./dashboardRouter');
const uploadApiRoutes = require('./uploadR2ApiRouter');

router.use('/', homeRoutes);
router.use('/', profileRoutes);
router.use('/', insightsRoutes);
router.use('/', insightsApiRoutes);
router.use('/', datasetRoutes);
router.use('/', datasetApiRoutes);
router.use('/', dashboardRoutes);
router.use('/', uploadApiRoutes);
router.use('/', requestRoutes);
router.use('/', aiRoutes);
router.use('/', feedbackformRoutes);
router.use('/', requestformRoutes);
router.use('/', comingsoonRoutes);
router.use('/', errorRoutes);

module.exports = router;